# NSSA Hugo Configuration
baseURL = 'https://n8n-project-460516.web.app'
defaultContentLanguage = 'zh'
defaultContentLanguageInSubdir = false

# Languages Configuration
[languages]
  [languages.zh]
    languageCode = 'zh-CN'
    languageName = '中文'
    title = 'NSSA - Not-So-Stubby Area'
    weight = 1
    [languages.zh.params]
      description = "NSSA 平台 - 历史研究与分析的交互式探索"
      keywords = ["历史研究", "战略分析", "交互式学习", "学术平台"]

  [languages.en]
    languageCode = 'en-US'
    languageName = 'English'
    title = 'NSSA - Not-So-Stubby Area'
    weight = 2
    [languages.en.params]
      description = "NSSA Platform - Interactive Exploration of Historical Research and Analysis"
      keywords = ["Historical Research", "Strategic Analysis", "Interactive Learning", "Academic Platform"]

# Build Configuration
buildDrafts = false
buildFuture = false
buildExpired = false
enableRobotsTXT = true
enableGitInfo = true

# Output Configuration
disableKinds = ['taxonomy', 'term']
enableEmoji = true

# Output formats - 只为首页生成 RSS
[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

# Markup Configuration
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = 'github'
    lineNos = false
    codeFences = true

# Menu Configuration
[menu]
  # Chinese Menu
  [[menu.main]]
    name = "技术专题"
    url = "/tech/"
    weight = 20
  [[menu.main]]
    name = "历史专题"
    url = "/history/"
    weight = 30
  [[menu.main]]
    name = "心理专题"
    url = "/psychology/"
    weight = 40
  [[menu.main]]
    name = "职场专题"
    url = "/workplace/"
    weight = 50
  [[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 60

# English Menu
[[languages.en.menu.main]]
  name = "Technology"
  url = "/en/tech/"
  weight = 20
[[languages.en.menu.main]]
  name = "History"
  url = "/en/history/"
  weight = 30
[[languages.en.menu.main]]
  name = "Psychology"
  url = "/en/psychology/"
  weight = 40
[[languages.en.menu.main]]
  name = "Workplace"
  url = "/en/workplace/"
  weight = 50
[[languages.en.menu.main]]
  name = "About"
  url = "/en/about/"
  weight = 60

# Params Configuration
[params]
  author = "NSSA Team"

  # Apple Style Design
  applestyle = true

  # Social and SEO
  [params.social]
    github = "https://github.com/Matthewyin/nssa"

  # Analytics and Performance
  [params.analytics]
    enabled = false

  [params.performance]
    lazyload = true
    minify = true

# Permalinks Configuration
[permalinks]
  topics = "/topics/:slug/"

# Related Content
[related]
  includeNewer = true
  threshold = 80
  toLower = false
  [[related.indices]]
    name = "keywords"
    weight = 100
  [[related.indices]]
    name = "tags"
    weight = 80

# Security Configuration
[security]
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^tailwindcss$', '^git$']
  [security.funcs]
    getenv = ['^HUGO_', '^CI$']
