name = "nssa-site"
main = "workers-site/index.js"
compatibility_date = "2024-08-29"

[site]
bucket = "./public"

# 环境变量配置
[vars]
ENVIRONMENT = "production"

# 自定义域名配置（生产环境）
# 注意：确保域名已在Cloudflare账户中正确配置
[[routes]]
pattern = "nssa.io/*"
zone_name = "nssa.io"
