name = "nssa-site"
main = "workers-site/index.js"
compatibility_date = "2024-08-29"

[site]
bucket = "./public"

# 环境变量配置
[vars]
ENVIRONMENT = "production"

# 自定义域名配置（生产环境）
[[domains]]
zone_name = "nssa.io"

[[routes]]
pattern = "nssa.io/*"

[[routes]]
pattern = "www.nssa.io/*"
