# wrangler.toml

# 给你的 Worker 项目起个名字
name = "nssa"

# 兼容性日期，使用一个近期的日期
compatibility_date = "2025-07-14"

# 主入口文件
main = "workers-site/index.js"

# 自定义域名路由配置
routes = [
  "nssa.io/*",
  "www.nssa.io/*"
]

# Workers Sites 配置
[site]
bucket = "./public"
