name = "nssa"
main = "workers-site/index.js"
compatibility_date = "2025-09-01"

[site]
bucket = "./public"

# 环境变量配置
[vars]
ENVIRONMENT = "production"

# 自定义域名配置（生产环境）
[[routes]]
pattern = "nssa.io/*"
zone_name = "nssa.io"

[[routes]]
pattern = "nssa.io/*"
zone_name = "nssa.io"
