# wrangler.toml

# 给你的 Worker 项目起个名字
name = "nssa"

# 兼容性日期，使用一个近期的日期
compatibility_date = "2025-07-14"

# 主入口文件
main = "workers-site/index.js"

# 自定义域名路由配置
routes = [
  { pattern = "nssa.io/*", zone_name = "nssa.io" },
  { pattern = "www.nssa.io/*", zone_name = "nssa.io" }
]

# Workers Sites 配置
[site]
bucket = "./public"

# KV 存储绑定 - 用于文章PV统计
[[kv_namespaces]]
binding = "ARTICLE_STATS"
id = "1d522d1cf0a547e28319cf5dc0f2d1cb"
