name: Deploy to Cloudflare Workers

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy NSSA to Cloudflare Workers

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build website
      run: |
        npm run css:build
        npx hugo --minify --gc

    - name: Verify build output
      run: |
        ls -la public/
        echo "Build completed successfully"

    - name: Check wrangler configuration
      run: |
        echo "Checking wrangler.toml:"
        cat wrangler.toml
        echo "Checking workers-site/index.js exists:"
        ls -la workers-site/index.js
        echo "Checking wrangler version:"
        npx wrangler --version

    - name: Test wrangler authentication
      run: npx wrangler whoami
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

    - name: Deploy to Cloudflare Workers
      run: npx wrangler deploy
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}


